 on:
      push:
         branches:
            - test1



 jobs:
      build:
          runs-on: ubuntu-latest
           


 
          steps: 
                             - name: 'Testing Githup action' 

                               run : pwd

                             - name: 'Testing printing'
                               run: echo ahmed        
                             - name: 'Before'
                               run: ls                 
                             - uses: actions/checkout@v3
                             - name: 'After'
                               run: ls                 
                             - name: 'Login to docker hup'
                               run: docker login --username ashosha110 --password dckr_pat_DAJ2R4SMP37Kbi3TYitffk8I32w
                              
