 on:
      push:
         branches:
            - test1



 jobs:
      build:
          runs-on: ubuntu-latest
           


 
          steps: 
                             - name: 'Testing Githup action' 

                               run : pwd

                             - name: 'Testing printing'
                               run: echo ahmed        
                             - name: 'Before'
                               run: ls                 
                             - uses: actions/checkout@v3
                             - name: 'After'
                               run: ls                 
                             - name: 'Login to docker hup'
                               run: docker login --username ${{secrets.USER}} --password ${{secrets.PASS}}
                             - name: 'Building docker image'
                               run: docker build -t ${{secrets.USER}}/new_image .
                             - name: 'Pushing to Docker hup'
                               run: docker push ${{secrets.USER}}/new_image
                               
                              
