
 
on:
      push:
         branches:
            - test1 
jobs:
                build:
                        runs-on: ubuntu-latest
                        steps: 
                               - name: 'Testing Githup action' 
                                 run: pwd
                               
